<script lang="ts">
  import { onMount } from 'svelte';
  import { brandApi, type Brand } from '$lib/api/brand.api';
  import { t } from '$lib/utils/i18n';
  import LoadingBar from '$lib/components/LoadingBar.svelte';
  import { dialogStore } from '$lib/stores/dialog.store';
  import { notificationStore } from '$lib/stores/notification.store';

  let brands: Brand[] = [];
  let loading = true;
  let showForm = false;
  let editingBrand: Brand | null = null;

  let formData = {
    name: '',
    slug: '',
    logo: '',
  };

  onMount(async () => {
    await loadBrands();
  });

  async function loadBrands() {
    loading = true;
    try {
      const response = await brandApi.getAll();
      brands = response.brands;
    } catch (e) {
      notificationStore.error(t('error.failedToLoad'));
    } finally {
      loading = false;
    }
  }

  function openForm(brand?: Brand) {
    if (brand) {
      editingBrand = brand;
      formData = {
        name: brand.name,
        slug: brand.slug,
        logo: brand.logo || '',
      };
    } else {
      editingBrand = null;
      formData = {
        name: '',
        slug: '',
        logo: '',
      };
    }
    showForm = true;
  }

  async function saveBrand() {
    try {
      if (editingBrand) {
        await brandApi.update(editingBrand.id, {
          ...formData,
          logo: formData.logo || undefined,
        });
      } else {
        await brandApi.create({
          ...formData,
          logo: formData.logo || undefined,
        });
      }
      showForm = false;
      await loadBrands();
    } catch (e: any) {
      notificationStore.error(e.response?.data?.error || t('error.failedToSave'));
    }
  }

  async function deleteBrand(id: string) {
    const confirmed = await dialogStore.confirm(t('alert.deleteBrand'), t('common.confirm'));
    if (!confirmed) return;
    try {
      await brandApi.delete(id);
      await loadBrands();
    } catch (e: any) {
      notificationStore.error(e.response?.data?.error || t('error.failedToDelete'));
    }
  }
</script>

<div>
  <div class="flex justify-between items-center mb-6">
    <h2 class="text-3xl font-bold">{t('brand.brands')}</h2>
    <button
      on:click={() => openForm()}
      class="px-6 py-2 bg-accent text-dark hover:bg-accent-muted transition-colors"
    >
      {t('brand.addBrand')}
    </button>
  </div>

  {#if showForm}
    <div class="bg-dark-light p-6 mb-6">
      <h3 class="text-xl font-medium mb-4">
        {editingBrand ? t('brand.editBrand') : t('brand.addBrand')}
      </h3>
      <div class="space-y-4">
        <div>
          <label for="brand-name" class="block text-sm font-medium mb-2"
            >{t('brand.brandName')} *</label
          >
          <input
            id="brand-name"
            type="text"
            bind:value={formData.name}
            class="w-full px-4 py-2 bg-white border border-gray-300 text-black"
            placeholder={t('brand.brandName')}
          />
        </div>
        <div>
          <label for="brand-slug" class="block text-sm font-medium mb-2"
            >{t('common.slug')} ({t('category.autoGenerated')})</label
          >
          <input
            id="brand-slug"
            type="text"
            bind:value={formData.slug}
            class="w-full px-4 py-2 bg-white border border-gray-300 text-black"
            placeholder="brand-slug"
          />
        </div>
        <div>
          <label for="brand-logo" class="block text-sm font-medium mb-2"
            >{t('brand.logo')} URL</label
          >
          <input
            id="brand-logo"
            type="url"
            bind:value={formData.logo}
            class="w-full px-4 py-2 bg-white border border-gray-300 text-black"
            placeholder="https://example.com/logo.png"
          />
          {#if formData.logo}
            <div class="mt-2">
              <img src={formData.logo} alt="Logo preview" class="h-16 object-contain" />
            </div>
          {/if}
        </div>
        <div class="flex gap-4">
          <button
            on:click={saveBrand}
            class="px-6 py-2 bg-accent text-dark hover:bg-accent-muted transition-colors"
          >
            {t('common.save')}
          </button>
          <button
            on:click={() => (showForm = false)}
            class="px-6 py-2 bg-white border border-gray-300 hover:bg-gray-100 transition-colors text-black"
          >
            {t('common.cancel')}
          </button>
        </div>
      </div>
    </div>
  {/if}

  {#if loading}
    <div class="w-full py-8"><LoadingBar /></div>
  {:else if brands.length === 0}
    <p class="text-accent-muted">{t('brand.noBrands')}</p>
  {:else}
    <div class="bg-white overflow-hidden">
      <table class="w-full">
        <thead class="bg-white">
          <tr>
            <th class="px-4 py-3 text-left text-sm font-medium">{t('brand.logo')}</th>
            <th class="px-4 py-3 text-left text-sm font-medium">{t('common.name')}</th>
            <th class="px-4 py-3 text-left text-sm font-medium">{t('common.slug')}</th>
            <th class="px-4 py-3 text-left text-sm font-medium">{t('menu.products')}</th>
            <th class="px-4 py-3 text-left text-sm font-medium">{t('common.actions')}</th>
          </tr>
        </thead>
        <tbody>
          {#each brands as brand}
            <tr class="border-t border-accent/10">
              <td class="px-4 py-3">
                {#if brand.logo}
                  <img src={brand.logo} alt={brand.name} class="h-12 w-12 object-contain" />
                {:else}
                  <span class="text-accent-muted">—</span>
                {/if}
              </td>
              <td class="px-4 py-3">
                <p class="font-medium">{brand.name}</p>
              </td>
              <td class="px-4 py-3">
                <span class="font-mono text-sm">{brand.slug}</span>
              </td>
              <td class="px-4 py-3">
                <span class="text-sm">{brand._count?.products || 0}</span>
              </td>
              <td class="px-4 py-3">
                <div class="flex gap-2">
                  <button
                    on:click={() => openForm(brand)}
                    class="px-3 py-1 bg-white border border-gray-300 text-sm hover:bg-gray-100 transition-colors text-black"
                  >
                    Edit
                  </button>
                  <button
                    on:click={() => deleteBrand(brand.id)}
                    class="px-3 py-1 bg-white border border-red-500/20 text-sm text-red-400 hover:bg-red-50 transition-colors"
                  >
                    Delete
                  </button>
                </div>
              </td>
            </tr>
          {/each}
        </tbody>
      </table>
    </div>
  {/if}
</div>
