/**
 * Seed data — self-contained so db:seed works in Docker (no ../src).
 * Keep in sync with src/types/settings.ts (DEFAULT_SETTINGS) and
 * src/scripts/init-default-countries-languages.ts (languages/countries).
 */

export const DEFAULT_SETTINGS: Record<string, unknown> = {
  reviewsEnabled: true,
  paymentGatewaysEnabled: true,
  stripeEnabled: false,
  paypalEnabled: false,
  brandsEnabled: true,
  showBrandFilter: true,
  loyaltyProgramEnabled: true,
  filtersEnabled: true,
  categoryFilterEnabled: true,
  priceFilterEnabled: true,
  brandFilterEnabled: true,
  searchEnabled: true,
  wishlistEnabled: true,
  compareEnabled: false,
  newsletterEnabled: true,
  socialLoginEnabled: false,
  lookbookEnabled: false,
  quickViewEnabled: true,
  productRecommendationsEnabled: true,
  recentlyViewedEnabled: false,
  fontFamily: 'Helvetica',
  fontSizeH1: '3rem',
  fontSizeH2: '2.25rem',
  fontSizeH3: '1.875rem',
  fontSizeH4: '1.5rem',
  fontSizeBody: '1rem',
  fontSizeSmall: '0.875rem',
  fontSizeButton: '1rem',
  textTransformUppercase: false,
  borderRadiusCard: '0',
  borderRadiusButton: '0',
  colorWhite: '#ffffff',
  colorDark: '#e8e5e5',
  colorDarkLight: '#f5f5f5',
  colorDarkLighter: '#e5e5e5',
  colorAccent: '#1c1b1b',
  colorAccentMuted: '#666666',
  colorAccentLight: '#ded9d9',
  colorBackground: '#ffffff',
  colorBackgroundSecondary: '#f9f9f9',
  colorBlack: '#000000',
  productPageDesign: 'classic',
  productImageAspectRatio: '9/16',
  productPageCompleteTheLookEnabled: true,
  productPageYouMightLikeEnabled: true,
  productPageYouMightLikeMode: 'similar',
  productPageYouViewedEnabled: true,
  shopGridColumns: '4',
  shopGridGap: '6',
  shopCardAspectRatio: '9/16',
  shopCardHoverImage: true,
  shopCardHoverAnimation: 'scale',
  shopCardVideoSupport: true,
  shopCardShowQuickAdd: false,
  imageBlurEnabled: false,
  pinterestEnabled: false,
  pinterestAccessToken: '',
  pinterestBoardId: '',
  frontendBaseUrl: 'http://localhost:5173',
  emailEnabled: false,
  emailProvider: 'CONSOLE',
  emailFromEmail: 'noreply@example.com',
  emailFromName: 'Fashion Store',
  emailNodemailerHost: '',
  emailNodemailerPort: 587,
  emailNodemailerSecure: false,
  emailNodemailerUser: '',
  emailNodemailerPassword: '',
  emailSendgridApiKey: '',
  emailAwsSesRegion: '',
  emailAwsSesAccessKeyId: '',
  emailAwsSesSecretAccessKey: '',
  emailResendApiKey: '',
  emailMailgunApiKey: '',
  emailMailgunDomain: '',
  emailMailgunRegion: 'us',
  emailBrevoApiKey: '',
  emailPrimaryColor: '#111111',
  emailSecondaryColor: '#737373',
  emailBackgroundColor: '#ffffff',
  emailTextColor: '#171717',
  emailFontFamily: "'Helvetica Neue', Helvetica, Arial, sans-serif",
  emailFontSize: '16px',
  emailButtonColor: '#111111',
  emailButtonTextColor: '#ffffff',
  deliveryTrackingEnabled: false,
  deliveryTrackingProvider: 'MANUAL',
  deliveryTrackingApiKey: '',
  deliveryTrackingApiUrl: '',
  deliveryTrackingAutoUpdate: false,
  deliveryTrackingUpdateInterval: 60,
  deliveryTrackingStatusMapping: JSON.stringify({
    RUSSIAN_POST: { REGISTERED: 'SHIPPED', IN_TRANSIT: 'SHIPPED', ARRIVED: 'SHIPPED', DELIVERED: 'DELIVERED', RETURNED: 'RETURNED', NOT_RECEIVED: 'RETURN_REQUESTED' },
    CDEK: { ACCEPTED: 'SHIPPED', IN_TRANSIT: 'SHIPPED', ARRIVED: 'SHIPPED', DELIVERED: 'DELIVERED', RETURNED: 'RETURNED' },
    DHL: { PRE_TRANSIT: 'SHIPPED', TRANSIT: 'SHIPPED', OUT_FOR_DELIVERY: 'SHIPPED', DELIVERED: 'DELIVERED', RETURNED: 'RETURNED', RETURNED_TO_SHIPPER: 'RETURNED', EXCEPTION: 'RETURN_REQUESTED' },
    FEDEX: { OC: 'SHIPPED', OD: 'DELIVERED', DL: 'DELIVERED', DP: 'SHIPPED', AF: 'SHIPPED', RS: 'RETURNED', CA: 'RETURN_REQUESTED' },
    UPS: { I: 'SHIPPED', P: 'SHIPPED', D: 'DELIVERED', X: 'RETURNED', R: 'RETURNED' },
    USPS: { 'In Transit': 'SHIPPED', 'Out for Delivery': 'SHIPPED', Delivered: 'DELIVERED', Returned: 'RETURNED', 'Return to Sender': 'RETURNED', Exception: 'RETURN_REQUESTED' },
    ARAMEX: { SH: 'SHIPPED', IT: 'SHIPPED', OD: 'SHIPPED', DR: 'DELIVERED', RT: 'RETURNED', RS: 'RETURNED', EX: 'RETURN_REQUESTED' },
  }),
  deliveryTrackingAutoMarkDelivered: false,
  deliveryTrackingAutoMarkNotReceived: false,
  deliveryTrackingNotReceivedDays: 30,
  deliveryTrackingAutoMarkReturned: false,
  deliveryTrackingProviders: '{}',
  analyticsEnabled: false,
  googleAnalyticsId: '',
  yandexMetricaId: '',
  registrationEnabled: true,
  loginEnabled: true,
  passwordMinLength: 8,
  passwordRequireUppercase: false,
  passwordRequireLowercase: true,
  passwordRequireNumbers: false,
  passwordRequireSpecialChars: false,
  loginRateLimitMaxAttempts: 5,
  loginRateLimitWindowMinutes: 15,
  registrationRateLimitMaxAttempts: 3,
  registrationRateLimitWindowMinutes: 60,
  accountLockoutEnabled: true,
  accountLockoutAttempts: 5,
  accountLockoutDurationMinutes: 30,
  emailVerificationRequired: false,
  captchaEnabled: false,
  captchaProvider: 'GOOGLE_RECAPTCHA_V3',
  captchaSiteKey: '',
  captchaSecretKey: '',
  captchaThreshold: 0.5,
  captchaRequiredForRegistration: false,
  captchaRequiredForLogin: false,
  oauthGoogleEnabled: false,
  oauthGoogleClientId: '',
  oauthGoogleClientSecret: '',
  oauthYandexEnabled: false,
  oauthYandexClientId: '',
  oauthYandexClientSecret: '',
  oauthVkontakteEnabled: false,
  oauthVkontakteClientId: '',
  oauthVkontakteClientSecret: '',
  oauthFacebookEnabled: false,
  oauthFacebookClientId: '',
  oauthFacebookClientSecret: '',
  oauthAppleEnabled: false,
  oauthAppleClientId: '',
  oauthAppleTeamId: '',
  oauthAppleKeyId: '',
  oauthApplePrivateKey: '',
  yandexDeliveryEnabled: false,
  yandexDeliveryApiToken: '',
  yandexGeocoderApiKey: '',
  yandexDeliverySenderName: '',
  yandexDeliverySenderPhone: '',
  yandexDeliverySenderAddress: '',
  yandexDeliverySenderCoordinates: '',
  yandexDeliveryPickupPointsCache: '',
  cartReservationGuestMinutes: 30,
  cartReservationRegisteredHours: 1,
  cartMaxQuantityPerProduct: 3,
  promoCodeCreationDisabled: false,
};

export const defaultLanguages = [
  { code: 'en', name: 'English', nameNative: 'English', flag: '🇬🇧' },
  { code: 'ru', name: 'Russian', nameNative: 'Русский', flag: '🇷🇺' },
  { code: 'fr', name: 'French', nameNative: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nameNative: 'Deutsch', flag: '🇩🇪' },
  { code: 'es', name: 'Spanish', nameNative: 'Español', flag: '🇪🇸' },
  { code: 'ja', name: 'Japanese', nameNative: '日本語', flag: '🇯🇵' },
  { code: 'zh', name: 'Chinese', nameNative: '中文', flag: '🇨🇳' },
  { code: 'ko', name: 'Korean', nameNative: '한국어', flag: '🇰🇷' },
  { code: 'ar', name: 'Arabic', nameNative: 'العربية', flag: '🇸🇦' },
  { code: 'hi', name: 'Hindi', nameNative: 'हिन्दी', flag: '🇮🇳' },
  { code: 'it', name: 'Italian', nameNative: 'Italiano', flag: '🇮🇹' },
];

export const defaultCountries = [
  { code: 'US', name: 'United States', nameNative: 'United States', currency: 'USD', language: 'en', taxRate: 0.08, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'GB', name: 'United Kingdom', nameNative: 'United Kingdom', currency: 'GBP', language: 'en', taxRate: 0.2, shippingCost: 8, freeShippingThreshold: 80 },
  { code: 'CA', name: 'Canada', nameNative: 'Canada', currency: 'CAD', language: 'en', taxRate: 0.13, shippingCost: 12, freeShippingThreshold: 100 },
  { code: 'AU', name: 'Australia', nameNative: 'Australia', currency: 'AUD', language: 'en', taxRate: 0.1, shippingCost: 15, freeShippingThreshold: 120 },
  { code: 'NZ', name: 'New Zealand', nameNative: 'New Zealand', currency: 'NZD', language: 'en', taxRate: 0.15, shippingCost: 15, freeShippingThreshold: 120 },
  { code: 'IE', name: 'Ireland', nameNative: 'Éire', currency: 'EUR', language: 'en', taxRate: 0.23, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'RU', name: 'Russia', nameNative: 'Россия', currency: 'RUB', language: 'ru', taxRate: 0.1, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'BY', name: 'Belarus', nameNative: 'Беларусь', currency: 'BYN', language: 'ru', taxRate: 0.2, shippingCost: 8, freeShippingThreshold: 80 },
  { code: 'KZ', name: 'Kazakhstan', nameNative: 'Қазақстан', currency: 'KZT', language: 'ru', taxRate: 0.12, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'UA', name: 'Ukraine', nameNative: 'Україна', currency: 'UAH', language: 'ru', taxRate: 0.2, shippingCost: 8, freeShippingThreshold: 80 },
  { code: 'FR', name: 'France', nameNative: 'France', currency: 'EUR', language: 'fr', taxRate: 0.2, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'BE', name: 'Belgium', nameNative: 'België', currency: 'EUR', language: 'fr', taxRate: 0.21, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'CH', name: 'Switzerland', nameNative: 'Schweiz', currency: 'CHF', language: 'fr', taxRate: 0.077, shippingCost: 12, freeShippingThreshold: 120 },
  { code: 'LU', name: 'Luxembourg', nameNative: 'Luxembourg', currency: 'EUR', language: 'fr', taxRate: 0.17, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'MC', name: 'Monaco', nameNative: 'Monaco', currency: 'EUR', language: 'fr', taxRate: 0.2, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'DE', name: 'Germany', nameNative: 'Deutschland', currency: 'EUR', language: 'de', taxRate: 0.19, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'AT', name: 'Austria', nameNative: 'Österreich', currency: 'EUR', language: 'de', taxRate: 0.2, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'LI', name: 'Liechtenstein', nameNative: 'Liechtenstein', currency: 'CHF', language: 'de', taxRate: 0.077, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'ES', name: 'Spain', nameNative: 'España', currency: 'EUR', language: 'es', taxRate: 0.21, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'MX', name: 'Mexico', nameNative: 'México', currency: 'MXN', language: 'es', taxRate: 0.16, shippingCost: 12, freeShippingThreshold: 100 },
  { code: 'AR', name: 'Argentina', nameNative: 'Argentina', currency: 'ARS', language: 'es', taxRate: 0.21, shippingCost: 15, freeShippingThreshold: 120 },
  { code: 'CO', name: 'Colombia', nameNative: 'Colombia', currency: 'COP', language: 'es', taxRate: 0.19, shippingCost: 12, freeShippingThreshold: 100 },
  { code: 'CL', name: 'Chile', nameNative: 'Chile', currency: 'CLP', language: 'es', taxRate: 0.19, shippingCost: 12, freeShippingThreshold: 100 },
  { code: 'PE', name: 'Peru', nameNative: 'Perú', currency: 'PEN', language: 'es', taxRate: 0.18, shippingCost: 12, freeShippingThreshold: 100 },
  { code: 'JP', name: 'Japan', nameNative: '日本', currency: 'JPY', language: 'ja', taxRate: 0.1, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'CN', name: 'China', nameNative: '中国', currency: 'CNY', language: 'zh', taxRate: 0.13, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'TW', name: 'Taiwan', nameNative: '台灣', currency: 'TWD', language: 'zh', taxRate: 0.05, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'HK', name: 'Hong Kong', nameNative: '香港', currency: 'HKD', language: 'zh', taxRate: 0, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'SG', name: 'Singapore', nameNative: 'Singapore', currency: 'SGD', language: 'zh', taxRate: 0.09, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'KR', name: 'South Korea', nameNative: '대한민국', currency: 'KRW', language: 'ko', taxRate: 0.1, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'SA', name: 'Saudi Arabia', nameNative: 'السعودية', currency: 'SAR', language: 'ar', taxRate: 0.15, shippingCost: 12, freeShippingThreshold: 100 },
  { code: 'AE', name: 'United Arab Emirates', nameNative: 'الإمارات العربية المتحدة', currency: 'AED', language: 'ar', taxRate: 0.05, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'EG', name: 'Egypt', nameNative: 'مصر', currency: 'EGP', language: 'ar', taxRate: 0.14, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'JO', name: 'Jordan', nameNative: 'الأردن', currency: 'JOD', language: 'ar', taxRate: 0.16, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'KW', name: 'Kuwait', nameNative: 'الكويت', currency: 'KWD', language: 'ar', taxRate: 0, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'QA', name: 'Qatar', nameNative: 'قطر', currency: 'QAR', language: 'ar', taxRate: 0, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'BH', name: 'Bahrain', nameNative: 'البحرين', currency: 'BHD', language: 'ar', taxRate: 0.1, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'OM', name: 'Oman', nameNative: 'عُمان', currency: 'OMR', language: 'ar', taxRate: 0.05, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'IN', name: 'India', nameNative: 'भारत', currency: 'INR', language: 'hi', taxRate: 0.18, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'IT', name: 'Italy', nameNative: 'Italia', currency: 'EUR', language: 'it', taxRate: 0.22, shippingCost: 8, freeShippingThreshold: 100 },
  { code: 'SM', name: 'San Marino', nameNative: 'San Marino', currency: 'EUR', language: 'it', taxRate: 0, shippingCost: 10, freeShippingThreshold: 100 },
  { code: 'VA', name: 'Vatican City', nameNative: 'Città del Vaticano', currency: 'EUR', language: 'it', taxRate: 0, shippingCost: 10, freeShippingThreshold: 100 },
];
