-- CreateTable
CREATE TABLE "header_settings" (
    "id" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "logoType" TEXT NOT NULL DEFAULT 'TEXT',
    "logoText" TEXT NOT NULL DEFAULT 'AWHSUM',
    "logoImageUrl" TEXT,
    "logoSvg" TEXT,
    "logoPosition" TEXT NOT NULL DEFAULT 'CENTER',
    "logoSize" TEXT NOT NULL DEFAULT 'text-2xl',
    "logoColor" TEXT NOT NULL DEFAULT '#000000',
    "logoLink" TEXT NOT NULL DEFAULT '/',
    "backgroundColor" TEXT NOT NULL DEFAULT '#ffffff',
    "textColor" TEXT NOT NULL DEFAULT '#000000',
    "borderColor" TEXT NOT NULL DEFAULT '#e5e7eb',
    "shadowEnabled" BOOLEAN NOT NULL DEFAULT true,
    "stickyEnabled" BOOLEAN NOT NULL DEFAULT true,
    "height" TEXT NOT NULL DEFAULT 'h-12',
    "categoryLinksEnabled" BOOLEAN NOT NULL DEFAULT true,
    "categoryLinksPosition" TEXT NOT NULL DEFAULT 'LEFT',
    "categoryLinksColor" TEXT NOT NULL DEFAULT '#4b5563',
    "categoryLinksHoverColor" TEXT NOT NULL DEFAULT '#000000',
    "categoryLinksActiveColor" TEXT NOT NULL DEFAULT '#000000',
    "categoryLinksFontSize" TEXT NOT NULL DEFAULT 'text-sm',
    "categoryLinksFontWeight" TEXT NOT NULL DEFAULT 'font-medium',
    "iconsEnabled" BOOLEAN NOT NULL DEFAULT true,
    "iconsPosition" TEXT NOT NULL DEFAULT 'RIGHT',
    "iconsColor" TEXT NOT NULL DEFAULT '#4b5563',
    "iconsHoverColor" TEXT NOT NULL DEFAULT '#000000',
    "iconsSize" TEXT NOT NULL DEFAULT 'w-5 h-5',
    "customIcons" JSONB,
    "categoryConditions" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedBy" TEXT,

    CONSTRAINT "header_settings_pkey" PRIMARY KEY ("id")
);
